database:
  host: localhost
  port: 32768
  user: username
  password: password
  database: dolphin

settings:
  debug: false
  max_tried: 24
  kick_when_shutdown: true
  backup: true
  sync:
    data: false
    achievement: false
    statistic: false