database:
  host: localhost
  port: 32768
  user: username
  password: password
  database: dolphin

redis:
  host: localhost
  port: 6379
#  auth: root
#  pass: root
  connect: 32
  timeout: 1000

settings:
  debug: false
  max_tried: 140
  kick_when_shutdown: true
  sync:
    data: false
    achievement: false
    statistic: false